import pdFileImg from "../assets/docExt/pdf.png";
import docxFileImg from "../assets/docExt/docx.png";
import xlsxFileImg from "../assets/docExt/xlsx.png";
import imgFileImg from "../assets/docExt/images.png";
import pptxFileImg from "../assets/docExt/pptx.png";
import archiveFolderImg from "../assets/archives.png";

export const data = [
  {
    id: 1,
    img: pdFileImg,
    name: "Resume",
    title: "My CV fr jobs",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
  },
  {
    id: 2,
    img: docxFileImg,
    name: "Resume",
    title: "My CV fr jobs",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
  },
  {
    id: 3,
    img: pdFileImg,
    name: "Resume",
    title: "My CV fr jobs",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
  },
  {
    id: 4,
    img: pdFileImg,
    name: "Resume",
    title: "My CV fr jobs",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
  },
  {
    id: 5,
    img: xlsxFileImg,
    name: "Choir List",
    title: "Choir List of names",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
  },
  {
    id: 6,
    img: pdFileImg,
    name: "Arabic Note",
    title: "My note book",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
  },
];

export const recycleBin = [
  {
    id: 1,
    img: pdFileImg,
    name: "Resume",
    title: "My CV fr jobs",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
  },
  {
    id: 2,
    img: docxFileImg,
    name: "Resume",
    title: "My CV fr jobs",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
  },
  {
    id: 3,
    img: pdFileImg,
    name: "Resume",
    title: "My CV fr jobs",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
  },
  {
    id: 4,
    img: pdFileImg,
    name: "Resume",
    title: "My CV fr jobs",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
  },
  {
    id: 5,
    img: xlsxFileImg,
    name: "Choir List",
    title: "Choir List of names",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
  },
  {
    id: 6,
    img: pdFileImg,
    name: "Arabic Note",
    title: "My note book",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
  },
  {
    id: 7,
    archiveFolderImg: archiveFolderImg,
    name: "Name",
    title: "Description",
    date: "May 26, 2019",
    time: "6:30 PM",
  },
];

export const archivesData = [
  {
    id: 1,
    img: archiveFolderImg,
    name: "Resume",
    title: "My CV fr jobs",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
  },
  {
    id: 2,
    img: archiveFolderImg,
    name: "Resume",
    title: "My CV fr jobs",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
  },
  {
    id: 3,
    img: archiveFolderImg,
    name: "Resume",
    title: "My CV fr jobs",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
  },
  {
    id: 4,
    img: archiveFolderImg,
    name: "Resume",
    title: "My CV fr jobs",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
  },
  {
    id: 5,
    img: archiveFolderImg,
    name: "Choir List",
    title: "Choir List of names",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
  },
  {
    id: 6,
    img: archiveFolderImg,
    name: "Arabic Note",
    title: "My note book",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
  },
];

export const notificationData = [
  {
    id: 1,
    title: "Notifcations Title",
    desc: "Description",
    date: "May 26, 2019",
    time: "6:30 PM",
  },
  {
    id: 2,
    title: "Notifcations Title",
    desc: "Description",
    date: "May 26, 2019",
    time: "6:30 PM",
  },
  {
    id: 3,
    title: "Notifcations Title",
    desc: "Description",
    date: "May 26, 2019",
    time: "6:30 PM",
  },
  {
    id: 4,
    title: "Notifcations Title",
    desc: "Description",
    date: "May 26, 2019",
    time: "6:30 PM",
  },
  {
    id: 5,
    title: "Notifcations Title",
    desc: "Description",
    date: "May 26, 2019",
    time: "6:30 PM",
  },
];

export const dataByCategories = [
  {
    id: 1,
    img: pdFileImg,
    name: "Resume",
    title: "My CV fr jobs",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
    category: "pdf",
  },
  {
    id: 2,
    img: pdFileImg,
    name: "Resume",
    title: "My CV fr jobs",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
    category: "pdf",
  },
  {
    id: 3,
    img: pdFileImg,
    name: "Resume",
    title: "My CV fr jobs",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
    category: "pdf",
  },
  {
    id: 4,
    img: pptxFileImg,
    name: "Choir List",
    title: "Choir List of names",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
    category: "pptx",
  },
  {
    id: 5,
    img: pptxFileImg,
    name: "Choir List",
    title: "Choir List of names",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
    category: "pptx",
  },
  {
    id: 6,
    img: pdFileImg,
    name: "Resume",
    title: "My CV fr jobs",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
    category: "pdf",
  },
  {
    id: 7,
    img: pdFileImg,
    name: "Resume",
    title: "My CV fr jobs",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
    category: "pdf",
  },
  {
    id: 8,
    img: docxFileImg,
    name: "Resume",
    title: "My CV fr jobs",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
    category: "docx",
  },
  {
    id: 9,
    img: docxFileImg,
    name: "Resume",
    title: "My CV fr jobs",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
    category: "docx",
  },
  {
    id: 10,
    img: docxFileImg,
    name: "Resume",
    title: "My CV fr jobs",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
    category: "docx",
  },
  {
    id: 11,
    img: imgFileImg,
    name: "Choir List",
    title: "Choir List of names",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
    category: "image",
  },
  {
    id: 12,
    img: imgFileImg,
    name: "Choir List",
    title: "Choir List of names",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
    category: "image",
  },
  {
    id: 13,
    img: imgFileImg,
    name: "Choir List",
    title: "Choir List of names",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
    category: "image",
  },

  {
    id: 14,
    img: docxFileImg,
    name: "Resume",
    title: "My CV fr jobs",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
    category: "docx",
  },
  {
    id: 15,
    img: docxFileImg,
    name: "Resume",
    title: "My CV fr jobs",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
    category: "docx",
  },
  {
    id: 16,
    img: imgFileImg,
    name: "Choir List",
    title: "Choir List of names",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
    category: "image",
  },
  {
    id: 17,
    img: imgFileImg,
    name: "Choir List",
    title: "Choir List of names",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
    category: "image",
  },
  {
    id: 18,
    img: xlsxFileImg,
    name: "Choir List",
    title: "Choir List of names",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
    category: "xlsx",
  },
  {
    id: 19,
    img: xlsxFileImg,
    name: "Choir List",
    title: "Choir List of names",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
    category: "xlsx",
  },
  {
    id: 20,
    img: xlsxFileImg,
    name: "Choir List",
    title: "Choir List of names",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
    category: "xlsx",
  },
  {
    id: 21,
    img: xlsxFileImg,
    name: "Choir List",
    title: "Choir List of names",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
    category: "xlsx",
  },
  {
    id: 22,
    img: xlsxFileImg,
    name: "Choir List",
    title: "Choir List of names",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
    category: "xlsx",
  },
  {
    id: 23,
    img: pptxFileImg,
    name: "Choir List",
    title: "Choir List of names",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
    category: "pptx",
  },
  {
    id: 24,
    img: pptxFileImg,
    name: "Choir List",
    title: "Choir List of names",
    archiveName: "My Credentials",
    date: "May 26, 2019",
    time: "6:30 PM",
    category: "pptx",
  },
];

export const accountSettingsData = [
  {
    id: 1,
    fullName: "Olawalebolaji Morenikeji",
    email: "olawalebolajimrenikeji2@gmail.com",
    phone: "2349044568530",
    password: "thevery3@goodBoy",
  },
];
